services:
  bixlerator:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./output_data:/app/output_data
      - ./bixlerator.db:/app/bixlerator.db
    restart: unless-stopped
